from typing import Protocol
from sсhemas import EmployeeDTO, EmployeeFilterDTO


class EmployeesRepositoryProtocol(Protocol):
    async def get_list(self, filter: EmployeeFilterDTO) -> EmployeeDTO: ...
    async def get_count(self, filter: EmployeeFilterDTO) -> int: ...
    async def create(self, dto: EmployeeDTO) -> EmployeeDTO: ...
    async def update(self, employee_uuid: str, employee: EmployeeDTO) -> EmployeeDTO: ...
    async def soft_delete(self, employee_uuid: str) -> EmployeeDTO: ...