from typing import Protocol, BinaryIO
from pathlib import Path
from sсhemas import EmployeeDTO, EmployeeFilterDTO


class EmployeesServiceProtocol(Protocol):
    async def get_list(self, filter: EmployeeFilterDTO) -> tuple[EmployeeDTO, int]:...
    async def create(self, filter: EmployeeDTO) -> EmployeeDTO:...
    async def update(self, employee_uuid: str, employee: EmployeeDTO) -> EmployeeDTO:...
    async def soft_delete(self, employee_uuid: str) -> EmployeeDTO:...


class FileServiceProtocol(Protocol):
    async def save_file_and_get_path(self, file_name: str, file: BinaryIO) -> Path: ...
    async def delete_file(file_name:str) -> Path: ...