from typing import Protocol
from schemas import EmployeesDTO, EmployeeFilterDTO


class EmployeesRepository:
    async def get_list(self, filter: EmployeeFilterDTO) -> EmployeesDTO: ...
    async def get_count(self, filter: EmployeeFilterDTO) -> int: ...
    async def update(self, employee_uuid: str, employee: EmployeesDTO) -> EmployeesDTO: ...
    async def soft_delete(self, employee_uuid: str) -> EmployeesDTO: ...